version: 2

project_name: gin-frontend

builds:
  - binary: "{{ .ProjectName }}"
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- if .IsSnapshot }}snapshot{{ else }}{{ .Version }}{{ end }}_
      {{- .Os }}_{{- .Arch }}
    files: []

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  skip: true
  mode: replace
  draft: false
  prerelease: "{{ .Tag | contains `-rc` || .Tag | contains `-beta` || .Tag | contains `-alpha` }}"

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    - title: Others
      regexp: '^.*?(build|chore|ci|docs|style|refactor|perf|test)(\([[:word:]]+\))??!?:.+$'
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - '^docs:'
      - '^test:'
