name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Update to v4
      - name: Set up Go
        uses: actions/setup-go@v5 # Update to v5
        with:
          go-version: '1.24' # Update Go version to match go.mod
      - name: Run Release Script
        run: bash scripts/release.sh
        env:
          VERSION: ${{ github.ref_name }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5 # Update to latest stable version
        with:
          version: '~> v2' # Specify GoReleaser v2.x to match config version
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
