# GoReleaser 自动发布工作流
# 触发条件：手动触发或推送带 v 前缀的标签
name: goreleaser

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: '选择发布类型'
        required: true
        type: choice
        options:
          - build-only
          - release
          - prerelease
        default: 'build-only'
      version:
        description: '发布版本 (仅在选择 release 时需要，格式如 v1.0.0)'
        required: false
        type: string
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gin-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # 使用更稳定的 Go 版本
          cache: true
      
      - name: Go Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Create git tag if not exists
        run: |
          if ! git describe --tags --exact-match &>/dev/null; then
            # 获取最新标签版本并递增
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            MAJOR=$(echo $LATEST_TAG | cut -d. -f1 | tr -d 'v')
            MINOR=$(echo $LATEST_TAG | cut -d. -f2)
            PATCH=$(echo $LATEST_TAG | cut -d. -f3)
            NEW_TAG="v$MAJOR.$MINOR.$((PATCH+1))"
            echo "No existing tag found for commit, creating $NEW_TAG"
            git tag $NEW_TAG
          fi

      - name: Set Release Version
        if: github.event_name == 'workflow_dispatch' && (github.event.inputs.release_type == 'release' || github.event.inputs.release_type == 'prerelease')
        run: |
          if [[ ! -z "${{ github.event.inputs.version }}" ]]; then
            git tag ${{ github.event.inputs.version }}
          else
            echo "Error: Version is required for release/prerelease mode"
            exit 1
          fi

      - name: Ensure Build Directory Exists
        if: github.event.inputs.release_type == 'build-only'
        run: mkdir -p gin-frontend/dist/

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.26.2
          args: >-
            ${{ github.event.inputs.release_type == 'build-only' && 'build --snapshot --output gin-frontend/dist/' ||
            github.event.inputs.release_type == 'prerelease' && 'release --clean --prerelease' ||
            'release --clean' }}
          workdir: gin-frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Build Directory
        if: github.event.inputs.release_type == 'build-only'
        run: ls -R gin-frontend/dist/

      - name: Upload Build Artifacts
        if: github.event.inputs.release_type == 'build-only'
        uses: actions/upload-artifact@v4
        with:
          name: goreleaser-binaries
          path: gin-frontend/dist/*
          if-no-files-found: error
          compression-level: 0

      - name: Upload Pre-release Artifacts
        if: github.event.inputs.release_type == 'prerelease'
        uses: actions/upload-artifact@v4
        with:
          name: prerelease-binaries
          path: gin-frontend/dist/*
          if-no-files-found: error
          compression-level: 0

      - name: Create Pre-release on GitHub
        if: github.event.inputs.release_type == 'prerelease'
        run: |
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
          if [[ -z "$TAG" ]]; then
            echo "Error: No tag found for prerelease."
            exit 1
          fi
          gh release create "$TAG" --prerelease --title "Pre-release $TAG" --notes "This is a pre-release version."

      - name: Upload Pre-release Artifacts to GitHub Release
        if: github.event.inputs.release_type == 'prerelease'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: gin-frontend/dist/*
          asset_name: prerelease-binaries
          label: "Pre-release binaries"

      - name: Delete Unreleased Tags
        if: github.event.inputs.release_type == 'build-only'
        run: |
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
          if [[ ! -z "$TAG" ]]; then
            echo "Deleting unreleased tag: $TAG"
            git tag -d $TAG
          else
            echo "No unreleased tag found."
          fi
