# GoReleaser 自动发布工作流
# 触发条件：手动触发或推送带 v 前缀的标签
name: goreleaser

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: '选择发布类型'
        required: true
        type: choice
        options:
          - build-only
          - release
        default: 'build-only'
      version:
        description: '发布版本 (仅在选择 release 时需要，格式如 v1.0.0)'
        required: false
        type: string
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gin-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # 使用更稳定的 Go 版本
          cache: true
      
      - name: Go Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Create git tag if not exists
        run: |
          if ! git describe --tags --exact-match &>/dev/null; then
            echo "No existing tag found, creating v0.1.0"
            git tag v0.1.0
          fi

      - name: Set Release Version
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.release_type == 'release'
        run: |
          if [[ ! -z "${{ github.event.inputs.version }}" ]]; then
            git tag ${{ github.event.inputs.version }}
          else
            echo "Error: Version is required for release mode"
            exit 1
          fi

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.26.2
          args: ${{ github.event.inputs.release_type == 'build-only' && 'build --snapshot' || 'release --clean' }}
          workdir: gin-frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        if: github.event.inputs.release_type == 'build-only'
        uses: actions/upload-artifact@v3
        with:
          name: goreleaser-build
          path: gin-frontend/dist/*
          retention-days: 5
