# GoReleaser 自动发布工作流
# 触发条件：手动触发或推送带 v 前缀的标签
name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gin-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # 使用更稳定的 Go 版本
          cache: true
      
      - name: Go Dependencies Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Create git tag if not exists
        run: |
          if ! git describe --tags --exact-match &>/dev/null; then
            echo "No existing tag found, creating v0.1.0"
            git tag v0.1.0
          fi

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.26.2
          args: release --clean
          workdir: gin-frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
